#!/bin/bash

alias aliases="cat ~/.bash_aliases"
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
#alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias g="git"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias ll="ls -l"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias rm="rm -rf --"
alias t="bin/phpunit -c app/ --stop-on-failure -v"
alias hto="rm -rf app/cache/test/* && bin/phpunit -c app/ src/Htg/Backend/GoogleLocationBundle/ && bin/phpunit -c app/ src/Htg/Backend/HometreeBuilderBundle/ && bin/phpunit -c app/ src/Vrt && bin/phpunit -c app/ src/Htg/HometreeForceBundle/"
alias ht="rm -rf app/cache/test/* && bin/phpunit -c app/ --stop-on-failure"
alias hf="npm install; npm run-script compile; app/console assets:install --symlink --relative"
alias hc="rm -rf app/cache/* && app/console cache:warmup -e dev"
alias hcp="rm -rf app/cache/* && app/console cache:warmup -e prod"
alias hi="cd /srv/import"
alias hb="cd /srv/backoffice"
alias dao="hb && composer dump-autoload -o"
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Load OS specific aliases.

. "aliases/$OS/bash_aliases"
